import Head from 'next/head'
import { Fragment } from 'react'
import Navbar from '../components/Navbar'
import Rights from '../components/Rights'
import '../styles/globals.scss'

function MyApp({ Component, pageProps }) {
  return (
    <Fragment>
        <Head>
        <title>Qari BookStore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Component {...pageProps} />
      <Rights/>
    </Fragment>
  )
}

export default MyApp
