import React, {Fragment} from 'react'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import Rights from '../components/Rights'
import '../styles/globals.scss'
import BooksProvider from "./api/booksContext"
export default function MyApp({ Component, pageProps }) {
  return (
    <Fragment>
      <BooksProvider>
          <Head>
            <title>Qari BookStore</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar/>
          <Component {...pageProps} />
          <Rights/>
      </BooksProvider >
    </Fragment>
  )
}